version: '3.4'

services:
  fedolphinshop:
    image: fedolphinshop
    build:
      context: fe-dolphinshop
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80

  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc*123
      MYSQL_USER: 'user1'
      MYSQL_PASS: 'password'
    volumes:
      - my-sql-db:/var/lib/mysql
    ports:
      - 3306:3306

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  my-sql-db: